FROM node:24-alpine AS build

WORKDIR /app

COPY package.json ./
RUN npm install

COPY nest-cli.json tsconfig.json ./
COPY src ./src

RUN npm run build


FROM node:24-alpine AS runtime

WORKDIR /app

ENV NODE_ENV=production

COPY package.json ./
RUN npm install --omit=dev

COPY --from=build /app/dist ./dist

USER node

EXPOSE 3000

CMD ["node", "dist/main.js"]
